set(CPACK_PACKAGE_NAME "robotology-additional-dependencies" CACHE STRING "")
set(CPACK_PACKAGE_VENDOR "iCub Facility, Istituto Italiano di Tecnologia (IIT)" CACHE STRING "")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Robotology Additional Dependencies" CACHE STRING "")
set(CPACK_PACKAGE_VERSION_MAJOR "0" CACHE STRING "")
set(CPACK_PACKAGE_VERSION_MINOR "4" CACHE STRING "")
set(CPACK_PACKAGE_VERSION_PATCH "0" CACHE STRING "")
set(CPACK_GENERATOR "IFW;ZIP" CACHE STRING "")
set(VCPKG_CPACK_TARGET_PORTS "libxml2;matio;winpcap;glew;glfw3" CACHE STRING "")
set(VCPKG_GIT_REPOSITORY "https://github.com/Microsoft/vcpkg.git" CACHE STRING "")
set(VCPKG_GIT_TAG "2019.08" CACHE STRING "")